# Generated by Django 5.2.6 on 2025-10-01 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="project",
            options={},
        ),
        migrations.RemoveField(
            model_name="project",
            name="cover_image",
        ),
        migrations.RemoveField(
            model_name="project",
            name="live_url",
        ),
        migrations.RemoveField(
            model_name="project",
            name="order",
        ),
        migrations.RemoveField(
            model_name="project",
            name="repo_url",
        ),
        migrations.RemoveField(
            model_name="project",
            name="status",
        ),
        migrations.RemoveField(
            model_name="project",
            name="tech_stack",
        ),
        migrations.AlterField(
            model_name="project",
            name="slug",
            field=models.SlugField(unique=True),
        ),
    ]
